name: Ejecutar pruebas con pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Usa la última versión de Python disponible

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Ejecutar pruebas con pytest
      run: pytest
